version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rayzriyaz
      POSTGRES_DB: status_track
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - redinet

  redis-master:
    image: redis:7
    container_name: redis-master
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    ports:
      - "6379:6379"
    networks:
      - redinet

  redis-replica1:
    image: redis:7
    container_name: redis-replica1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--replicaof", "redis-master", "6379"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-replica1-data:/data
    ports:
      - "6380:6379"
    networks:
      - redinet
    depends_on:
      - redis-master

  redis-replica2:
    image: redis:7
    container_name: redis-replica2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--replicaof", "redis-master", "6379"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-replica2-data:/data
    ports:
      - "6381:6379"
    networks:
      - redinet
    depends_on:
      - redis-master

  sentinel1:
    image: redis:7
    container_name: sentinel1
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf", "--sentinel", "announce-port", "26379"]
    volumes:
      - ./docker/sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/sentinel/data1:/data
    ports:
      - "26379:26379"
    networks:
      - redinet
    depends_on:
      - redis-master

  sentinel2:
    image: redis:7
    container_name: sentinel2
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf", "--sentinel", "announce-port", "26380"]
    volumes:
      - ./docker/sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/sentinel/data2:/data
    ports:
      - "26380:26379"
    networks:
      - redinet
    depends_on:
      - redis-master

  sentinel3:
    image: redis:7
    container_name: sentinel3
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf", "--sentinel", "announce-port", "26381"]
    volumes:
      - ./docker/sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/sentinel/data3:/data
    ports:
      - "26381:26379"
    networks:
      - redinet
    depends_on:
      - redis-master
  app:
    build: .
    container_name: status-tracking-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/status_track
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rayzriyaz
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8092:8093"
    networks:
      - redinet
    depends_on:
      - postgres
      - redis-master
      - sentinel1
      - sentinel2
      - sentinel3

volumes:
  pgdata:
  redis-master-data:
  redis-replica1-data:
  redis-replica2-data:

networks:
  redinet:
    driver: bridge
